INFO:root:


자동화 테스트 시작



INFO:root:더보기 테스트 시작
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103fc20d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104196b90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041974d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104164310>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d1290>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d1c10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d2b90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d3d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e4750>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d3250>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d19d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104164610>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104197750>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104196810>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e5e10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e6950>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7350>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7d50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ecd90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041eda90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ee410>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104196cd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104164210>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7c90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7250>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e6010>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d25d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ed7d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ec050>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ef590>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f4210>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f5410>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d1450>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e6ed0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e6950>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7f90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104196a10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041979d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ecb10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ec2d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f5e50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f6350>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ec090>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104196e10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104197b90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e5e90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e6d10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7a10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104197550>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f78d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1042080d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104209350>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104209d50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10420a5d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f7c50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e79d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7ad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f7690>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104197b90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104164210>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d1310>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104208ed0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10420afd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ec490>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104210ad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103db25d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104197d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104197ed0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7090>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d0b50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f7a50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f7e50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10420b610>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104208ad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104211850>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f6d10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f7b90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d25d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e6c90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1040b1dd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041943d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041effd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104212e90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1042135d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1042207d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104221090>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104221990>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104213a90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1031e7ad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ec590>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ed6d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041e7f50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041d1690>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041f59d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104209dd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1042204d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104223290>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104223c50>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1031e7ad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104223010>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1042212d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104221c90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104210710>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104213cd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104211910>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104212f90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104211350>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10420bc90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104212150>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104213d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1042139d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session/9848f5bb-f1e9-4ce6-a21c-5dadcafe488f/element
INFO:root:더보기 테스트 종료
INFO:root:


자동화 테스트 시작



INFO:root:더보기 테스트 시작
INFO:root:


자동화 테스트 시작



INFO:root:핀코드 로그인 테스트 시작
INFO:root:로그인 : PASS
INFO:root:핀코드 로그인 테스트 종료
INFO:root:마이홈 테스트 시작
INFO:root:마이홈 상단 퀵 메뉴 영역 노출 및 진입 테스트 시작
WARNING:root:마이홈 상단 메뉴 퀵 영역 노출 에러 발생 : Message: An element could not be located on the page using the given search parameters.
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
INFO:root:마이홈 금융생활 선택 후 자산목록 진입 테스트 시작
INFO:root:['PASS', 'PASS', 'PASS', 'PASS']
INFO:root:금융생활 선택 후 자산목록 진입 : PASS
INFO:root:마이홈 금융생활 선택 후 자산목록 진입 테스트 종료
INFO:root:마이홈 금융생활 출금 일정 노출 테스트 시작
INFO:root:사용자ID 3650813
INFO:root:3650813
INFO:root:['eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MzY1MDgxMywiZXhwIjoxNzYzMDkyODU5LCJpYXQiOjE3MzE1NTY4NTl9.LwwCwnEM3-hUEX1k75wvCGJ60gb1RibqIWsUJDZ4Wms']
INFO:root:{'result': {'code': '00000', 'desc': 'OK'}, 'data': {'totalCheckingAccountBalanceAmount': 420000, 'totalCardPayAmount': 352954, 'isTotalCardInfoMydataError': False, 'isTotalCheckingInfoMydataError': False, 'repayPlanInfo': [{'repayDate': '2024-11-19T00:00:00', 'assetList': [{'accountId': 32682384, 'productName': '주택도시기금 버팀목전세자금(신혼가구)', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 228688, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}, {'repayDate': '2024-11-26T00:00:00', 'assetList': [{'accountId': 32682383, 'productName': '주택도시기금 청년취업(창업) 전세자금대출', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 135519, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}], 'errorList': []}}
INFO:root:{'result': {'code': '00000', 'desc': 'OK'}, 'data': {'totalCheckingAccountBalanceAmount': 420000, 'totalCardPayAmount': 352954, 'isTotalCardInfoMydataError': False, 'isTotalCheckingInfoMydataError': False, 'repayPlanInfo': [{'repayDate': '2024-11-19T00:00:00', 'assetList': [{'accountId': 32682384, 'productName': '주택도시기금 버팀목전세자금(신혼가구)', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 228688, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}, {'repayDate': '2024-11-26T00:00:00', 'assetList': [{'accountId': 32682383, 'productName': '주택도시기금 청년취업(창업) 전세자금대출', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 135519, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}], 'errorList': []}}
INFO:root:금융생활 출금일정 노출 결과 : FAIL
INFO:root:마이홈 금융생활 출금 일정 노출 테스트 종료
INFO:root:마이홈 금융생활 쓸 수 있는 현금 노출 및 진입 테스트 시작
INFO:root:{'result': {'code': '00000', 'desc': 'OK'}, 'data': {'totalCheckingAccountBalanceAmount': 420000, 'totalCardPayAmount': 352954, 'isTotalCardInfoMydataError': False, 'isTotalCheckingInfoMydataError': False, 'repayPlanInfo': [{'repayDate': '2024-11-19T00:00:00', 'assetList': [{'accountId': 32682384, 'productName': '주택도시기금 버팀목전세자금(신혼가구)', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 228688, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}, {'repayDate': '2024-11-26T00:00:00', 'assetList': [{'accountId': 32682383, 'productName': '주택도시기금 청년취업(창업) 전세자금대출', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 135519, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}], 'errorList': []}}
INFO:root:마이홈 금융생활 쓸 수 있는 현금 노출 및 진입 : PASS
INFO:root:마이홈 금융생활 쓸 수 있는 현금 노출 및 진입 테스트 종료
INFO:root:마이홈 금융생활 카드 사용금액 노출 및 진입 테스트 시작
INFO:root:{'result': {'code': '00000', 'desc': 'OK'}, 'data': {'totalCheckingAccountBalanceAmount': 420000, 'totalCardPayAmount': 352954, 'isTotalCardInfoMydataError': False, 'isTotalCheckingInfoMydataError': False, 'repayPlanInfo': [{'repayDate': '2024-11-19T00:00:00', 'assetList': [{'accountId': 32682384, 'productName': '주택도시기금 버팀목전세자금(신혼가구)', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 228688, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}, {'repayDate': '2024-11-26T00:00:00', 'assetList': [{'accountId': 32682383, 'productName': '주택도시기금 청년취업(창업) 전세자금대출', 'orgCode': 'A1AAEM0000', 'orgLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori.png', 'orgBackgroundLogoUrl': 'https://cdn.finda.co.kr/images/bank/app/bank_symbol_woori_bg.png', 'orgName': '우리은행', 'assetType': 'LOAN', 'repayAmount': 135519, 'seqNo': None, 'repaymentStatus': 'UNKNOWN', 'repayAccountStatus': 'AMPLE_BALANCE', 'mydataError': False}]}], 'errorList': []}}
INFO:root:마이홈 금융생활 카드 사용금액 노출 및 진입 : PASS
INFO:root:마이홈 금융생활 카드 사용금액 노출 및 진입 테스트 종료
INFO:root:마이홈 신용점수 진입 후 신용점수 노출 테스트 시작
INFO:root:마이홈 신용점수 진입 후 신용점수 노출결과 : PASS
ERROR:root:credit_score_back : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
INFO:root:마이홈 신용점수 진입 후 신용점수 노출 테스트 종료
INFO:root:마이홈 테스트 종료
INFO:root:더보기 테스트 시작
INFO:root:더보기 진입 테스트 시작
INFO:root:더보기 탭 진입 : PASS
INFO:root:더보기 진입 테스트 시작
INFO:root:내대출 진입 테스트 시작
INFO:root:['PASS', 'PASS', 'PASS', 'PASS']
INFO:root:내 대출 진입 : PASS
INFO:root:내대출 진입 테스트 종료
INFO:root:채팅문의 진입 테스트 시작
WARNING:root:채널톡 진입 에러 발생 : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
INFO:root:채팅문의 진입 테스트 종료
INFO:root:자주묻는 질문 진입 및 상세 페이지 노출 테스트 시작
INFO:root:['Error', 'Error', 'Error', 'Error']
INFO:root:자주 묻는 질문 진입 : FAIL
ERROR:root:qna_click_a : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
ERROR:root:qna_click_a : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
ERROR:root:qna_click_a : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
WARNING:root:자주묻는질문진입_A 에러 발생 : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
ERROR:root:qna_click_a : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
ERROR:root:qna_click_b : Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
    at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
